#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""This module contains common static definitions used by the application,
that are not defined in the config file.
This include:
    - application version, license, etc.
    - application folder; this depends whether app runs as a Python process or as
      pyinstaller bundle
    - global application data

Logging and config file management are implemented in the log and config_handler submodules.
"""

import sys

from pathlib import Path

__author__ = "Moxa Europe"
__license__ = "GPLv3.0"
__version__ = '4.1.5'
__status__ = "Development"

# Check whether the app is running from source or whether it is bundled ("frozen").
#
# See: https://pyinstaller.readthedocs.io/en/stable/runtime-information.html#
#
if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
    # running in a PyInstaller bundle
    RUNNING_BUNDLE = True
else:
    # running in a normal Python process
    RUNNING_BUNDLE = False

# BUNDLE_DIR is where the app is located; it is in temporary folder (/tmp)
# when running the executable bundle generated by PyInstaller.
#
# APP_DIR is the top application directory when running in a normal Python process,
# or the directory where the executable bundle is located when running pyinstaller bundle
#
# ROOT_DIR is the top level repo directory.
# When running as a bundle it is set the same as APP_DIR,
# this is where 'resources' directory is located.
#
if RUNNING_BUNDLE:
    # running in a PyInstaller bundle
    # noinspection PyProtectedMember,PyUnresolvedReferences
    BUNDLE_DIR = Path(sys._MEIPASS)
    APP_DIR = Path(sys.executable).parent
    ROOT_DIR = APP_DIR
else:
    # running in a normal Python process
    BUNDLE_DIR = None
    # The src dir containing the main app script
    APP_DIR = Path(__file__).parent.parent
    # The main repo dir. The 'src', 'resources' subdirectories are located here
    ROOT_DIR = APP_DIR.parent
